name = "regularPathDelay"
version = "0.3.0"
keywords = ["enumeration", "skew-symmetric-graphs", "formal-verification"]
defaultTargets = ["RegularPathDelay", "Challenge", "Solution"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "cslib"
scope = "leanprover"
rev = "5ccce0ebe0d94fbad8cc21a1822500b82428b5a2"

[[lean_lib]]
name = "RegularPathDelay"

[[lean_lib]]
name = "RegularPathDelayEnumeration"
roots = ["RegularPathDelayEnumeration"]

[[lean_lib]]
name = "RegularPathDelayTrace"
roots = ["RegularPathDelayTrace"]

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
