import ZombieDamage.Certificates

/-! Generated by verification/generate_lean_data.py.
All 94 tasks are embedded; the 19-task symmetry reduction is NOT
assumed by these theorem statements. See VERIFICATION.md for build evidence.
Raw JSON SHA-256: 73f398dd73a647faacef4aff025ccd4abc11c7df80ff668ba5f467452eba32d1
-/
namespace ZombieDamage.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace K2_3

def adj (u v : Fin 8) : Bool :=
  match u.val, v.val with
  | 0, 2 => true
  | 0, 3 => true
  | 0, 4 => true
  | 1, 2 => true
  | 1, 3 => true
  | 1, 4 => true
  | 2, 0 => true
  | 2, 1 => true
  | 2, 5 => true
  | 3, 0 => true
  | 3, 1 => true
  | 3, 6 => true
  | 4, 0 => true
  | 4, 1 => true
  | 4, 7 => true
  | 5, 2 => true
  | 6, 3 => true
  | 7, 4 => true
  | _, _ => false

namespace task_00

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 5, 2⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 3⟩, 6, 1⟩
  | 2 => ⟨⟨true, 1, 3⟩, 6, 1⟩
  | _ => ⟨⟨true, 2, 0⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_00

namespace task_01

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 5, 2⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 4⟩, 7, 1⟩
  | 2 => ⟨⟨true, 1, 4⟩, 7, 1⟩
  | _ => ⟨⟨true, 2, 0⟩, 4, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_01

namespace task_02

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 0
  allowedExit v := decide (v.val = 6) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 2, 0⟩, 3, 2⟩
  | 1 => ⟨⟨false, 5, 2⟩, 0, 3⟩
  | 2 => ⟨⟨true, 0, 3⟩, 6, 1⟩
  | _ => ⟨⟨true, 1, 3⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_02

namespace task_03

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 1
  allowedExit v := decide (v.val = 6) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 2, 1⟩, 3, 2⟩
  | 1 => ⟨⟨false, 5, 2⟩, 1, 3⟩
  | 2 => ⟨⟨true, 0, 3⟩, 6, 1⟩
  | _ => ⟨⟨true, 1, 3⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_03

namespace task_04

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 2
  allowedExit v := decide (v.val = 6) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 5, 2⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 3⟩, 6, 1⟩
  | 2 => ⟨⟨true, 1, 3⟩, 6, 1⟩
  | _ => ⟨⟨true, 2, 0⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_04

namespace task_05

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 3
  allowedExit v := decide (v.val = 6) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 3⟩, 6, 1⟩
  | 1 => ⟨⟨false, 1, 3⟩, 6, 1⟩
  | 2 => ⟨⟨false, 2, 0⟩, 3, 2⟩
  | _ => ⟨⟨false, 5, 2⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_05

namespace task_06

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 4
  allowedExit v := decide (v.val = 6) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 7, 1⟩
  | 1 => ⟨⟨false, 1, 4⟩, 7, 1⟩
  | 2 => ⟨⟨false, 2, 0⟩, 4, 2⟩
  | _ => ⟨⟨false, 5, 2⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 5, 2⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 5, 2⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_06

namespace task_07

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 5)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 3⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | 2 => ⟨⟨true, 1, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 3, 0⟩, 2, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_07

namespace task_08

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 3⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 4⟩, 7, 1⟩
  | 2 => ⟨⟨true, 1, 4⟩, 7, 1⟩
  | _ => ⟨⟨true, 3, 0⟩, 4, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_08

namespace task_09

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 0
  allowedExit v := decide (v.val = 5) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 0⟩, 2, 2⟩
  | 1 => ⟨⟨false, 6, 3⟩, 0, 3⟩
  | 2 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 1, 2⟩, 5, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_09

namespace task_10

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 1
  allowedExit v := decide (v.val = 5) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 1⟩, 2, 2⟩
  | 1 => ⟨⟨false, 6, 3⟩, 1, 3⟩
  | 2 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 1, 2⟩, 5, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_10

namespace task_11

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 2
  allowedExit v := decide (v.val = 5) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 5, 1⟩
  | 1 => ⟨⟨false, 1, 2⟩, 5, 1⟩
  | 2 => ⟨⟨false, 3, 0⟩, 2, 2⟩
  | _ => ⟨⟨false, 6, 3⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_11

namespace task_12

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 3
  allowedExit v := decide (v.val = 5) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 3⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | 2 => ⟨⟨true, 1, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 3, 0⟩, 2, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_12

namespace task_13

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 4
  allowedExit v := decide (v.val = 5) || decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 7, 1⟩
  | 1 => ⟨⟨false, 1, 4⟩, 7, 1⟩
  | 2 => ⟨⟨false, 3, 0⟩, 4, 2⟩
  | _ => ⟨⟨false, 6, 3⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 6, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_13

namespace task_14

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 5)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 4⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | 2 => ⟨⟨true, 1, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 4, 0⟩, 2, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_14

namespace task_15

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := none
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 4⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 3⟩, 6, 1⟩
  | 2 => ⟨⟨true, 1, 3⟩, 6, 1⟩
  | _ => ⟨⟨true, 4, 0⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_15

namespace task_16

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 0
  allowedExit v := decide (v.val = 5) || decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 4, 0⟩, 2, 2⟩
  | 1 => ⟨⟨false, 7, 4⟩, 0, 3⟩
  | 2 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 1, 2⟩, 5, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_16

namespace task_17

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 1
  allowedExit v := decide (v.val = 5) || decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 4, 1⟩, 2, 2⟩
  | 1 => ⟨⟨false, 7, 4⟩, 1, 3⟩
  | 2 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 1, 2⟩, 5, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (1 : Fin 4) (by decide)

end task_17

namespace task_18

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 2
  allowedExit v := decide (v.val = 5) || decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 5, 1⟩
  | 1 => ⟨⟨false, 1, 2⟩, 5, 1⟩
  | 2 => ⟨⟨false, 4, 0⟩, 2, 2⟩
  | _ => ⟨⟨false, 7, 4⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_18

namespace task_19

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 3
  allowedExit v := decide (v.val = 5) || decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 3⟩, 6, 1⟩
  | 1 => ⟨⟨false, 1, 3⟩, 6, 1⟩
  | 2 => ⟨⟨false, 4, 0⟩, 3, 2⟩
  | _ => ⟨⟨false, 7, 4⟩, 0, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (3 : Fin 4) (by decide)

end task_19

namespace task_20

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 5)
  target := some 4
  allowedExit v := decide (v.val = 5) || decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 4⟩, 0, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 5, 1⟩
  | 2 => ⟨⟨true, 1, 2⟩, 5, 1⟩
  | _ => ⟨⟨true, 4, 0⟩, 2, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 4⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 10 ⟨false, 7, 4⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    10 (0 : Fin 4) (by decide)

end task_20

end K2_3

namespace K3_3_minus_edge

def adj (u v : Fin 8) : Bool :=
  match u.val, v.val with
  | 0, 4 => true
  | 0, 5 => true
  | 0, 6 => true
  | 1, 3 => true
  | 1, 4 => true
  | 1, 5 => true
  | 2, 3 => true
  | 2, 4 => true
  | 2, 5 => true
  | 3, 1 => true
  | 3, 2 => true
  | 3, 7 => true
  | 4, 0 => true
  | 4, 1 => true
  | 4, 2 => true
  | 5, 0 => true
  | 5, 1 => true
  | 5, 2 => true
  | 6, 0 => true
  | 7, 3 => true
  | _, _ => false

namespace task_00

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 0⟩, 4, 4⟩
  | 1 => ⟨⟨true, 0, 4⟩, 1, 3⟩
  | 2 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 3 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 4 => ⟨⟨true, 4, 1⟩, 3, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 6) (by decide)

end task_00

namespace task_01

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 0
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 0⟩, 4, 4⟩
  | 1 => ⟨⟨true, 0, 4⟩, 1, 3⟩
  | 2 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 3 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 4 => ⟨⟨true, 4, 1⟩, 3, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 6) (by decide)

end task_01

namespace task_02

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 1
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 1, 3⟩
  | 1 => ⟨⟨false, 4, 1⟩, 3, 2⟩
  | 2 => ⟨⟨false, 5, 1⟩, 3, 2⟩
  | 3 => ⟨⟨false, 6, 0⟩, 4, 4⟩
  | 4 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 2, 3⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 6) (by decide)

end task_02

namespace task_03

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 2
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 2, 3⟩
  | 1 => ⟨⟨false, 4, 2⟩, 3, 2⟩
  | 2 => ⟨⟨false, 5, 2⟩, 3, 2⟩
  | 3 => ⟨⟨false, 6, 0⟩, 4, 4⟩
  | 4 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 2, 3⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 6) (by decide)

end task_03

namespace task_04

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 3
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 1, 3⟩
  | 1 => ⟨⟨false, 1, 3⟩, 7, 1⟩
  | 2 => ⟨⟨false, 2, 3⟩, 7, 1⟩
  | 3 => ⟨⟨false, 4, 1⟩, 3, 2⟩
  | 4 => ⟨⟨false, 5, 1⟩, 3, 2⟩
  | _ => ⟨⟨false, 6, 0⟩, 4, 4⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (5 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (5 : Fin 6) (by decide)

end task_04

namespace task_05

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 4
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 1, 3⟩
  | 1 => ⟨⟨false, 6, 0⟩, 4, 4⟩
  | 2 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 3 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 4 => ⟨⟨true, 4, 1⟩, 3, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 6) (by decide)

end task_05

namespace task_06

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 5
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 5⟩, 1, 3⟩
  | 1 => ⟨⟨false, 6, 0⟩, 5, 4⟩
  | 2 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 3 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 4 => ⟨⟨true, 4, 1⟩, 3, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 6) (by decide)

end task_06

namespace task_07

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := none
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 3⟩, 1, 4⟩
  | 1 => ⟨⟨true, 1, 4⟩, 0, 2⟩
  | 2 => ⟨⟨true, 2, 4⟩, 0, 2⟩
  | 3 => ⟨⟨true, 3, 1⟩, 4, 3⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 6) (by decide)

end task_07

namespace task_08

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 0
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 4⟩, 0, 2⟩
  | 1 => ⟨⟨false, 2, 4⟩, 0, 2⟩
  | 2 => ⟨⟨false, 3, 1⟩, 4, 3⟩
  | 3 => ⟨⟨false, 4, 0⟩, 6, 1⟩
  | 4 => ⟨⟨false, 5, 0⟩, 6, 1⟩
  | _ => ⟨⟨false, 7, 3⟩, 1, 4⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (5 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (5 : Fin 6) (by decide)

end task_08

namespace task_09

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 1
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 1⟩, 4, 3⟩
  | 1 => ⟨⟨false, 7, 3⟩, 1, 4⟩
  | 2 => ⟨⟨true, 1, 4⟩, 0, 2⟩
  | 3 => ⟨⟨true, 2, 4⟩, 0, 2⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 6) (by decide)

end task_09

namespace task_10

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 2
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 2⟩, 4, 3⟩
  | 1 => ⟨⟨false, 7, 3⟩, 2, 4⟩
  | 2 => ⟨⟨true, 1, 4⟩, 0, 2⟩
  | 3 => ⟨⟨true, 2, 4⟩, 0, 2⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 6) (by decide)

end task_10

namespace task_11

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 3
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 3⟩, 1, 4⟩
  | 1 => ⟨⟨true, 1, 4⟩, 0, 2⟩
  | 2 => ⟨⟨true, 2, 4⟩, 0, 2⟩
  | 3 => ⟨⟨true, 3, 1⟩, 4, 3⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 6) (by decide)

end task_11

namespace task_12

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 4
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 4⟩, 0, 2⟩
  | 1 => ⟨⟨false, 2, 4⟩, 0, 2⟩
  | 2 => ⟨⟨false, 3, 1⟩, 4, 3⟩
  | 3 => ⟨⟨false, 7, 3⟩, 1, 4⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 6) (by decide)

end task_12

namespace task_13

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 5
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 6) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 5⟩, 0, 2⟩
  | 1 => ⟨⟨false, 2, 5⟩, 0, 2⟩
  | 2 => ⟨⟨false, 3, 1⟩, 5, 3⟩
  | 3 => ⟨⟨false, 7, 3⟩, 1, 4⟩
  | 4 => ⟨⟨true, 4, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 5, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 6))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 6) (by decide)

end task_13

end K3_3_minus_edge

namespace triangular_prism_minus_triangle_edge

def adj (u v : Fin 8) : Bool :=
  match u.val, v.val with
  | 0, 2 => true
  | 0, 3 => true
  | 0, 6 => true
  | 1, 2 => true
  | 1, 4 => true
  | 1, 7 => true
  | 2, 0 => true
  | 2, 1 => true
  | 2, 5 => true
  | 3, 0 => true
  | 3, 4 => true
  | 3, 5 => true
  | 4, 1 => true
  | 4, 3 => true
  | 4, 5 => true
  | 5, 2 => true
  | 5, 3 => true
  | 5, 4 => true
  | 6, 0 => true
  | 7, 1 => true
  | _, _ => false

namespace task_00

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 0⟩, 2, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 1, 2⟩
  | _ => ⟨⟨true, 2, 1⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 3) (by decide)

end task_00

namespace task_01

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 0
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 0⟩, 2, 3⟩
  | 1 => ⟨⟨true, 0, 2⟩, 1, 2⟩
  | _ => ⟨⟨true, 2, 1⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 3) (by decide)

end task_01

namespace task_02

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 1
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 1, 2⟩
  | 1 => ⟨⟨false, 2, 1⟩, 7, 1⟩
  | _ => ⟨⟨false, 6, 0⟩, 2, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (2 : Fin 3) (by decide)

end task_02

namespace task_03

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 2
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 1, 2⟩
  | 1 => ⟨⟨false, 6, 0⟩, 2, 3⟩
  | _ => ⟨⟨true, 2, 1⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 3) (by decide)

end task_03

namespace task_04

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 3
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 3⟩, 4, 3⟩
  | 1 => ⟨⟨false, 6, 0⟩, 3, 4⟩
  | 2 => ⟨⟨true, 3, 4⟩, 1, 2⟩
  | _ => ⟨⟨true, 4, 1⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 4) (by decide)

end task_04

namespace task_05

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 4
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 3⟩, 4, 3⟩
  | 1 => ⟨⟨false, 3, 4⟩, 1, 2⟩
  | 2 => ⟨⟨false, 6, 0⟩, 3, 4⟩
  | _ => ⟨⟨true, 4, 1⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (2 : Fin 4) (by decide)

end task_05

namespace task_06

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 5
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 12) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 5, 7⟩
  | 1 => ⟨⟨false, 2, 5⟩, 4, 6⟩
  | 2 => ⟨⟨false, 3, 5⟩, 2, 3⟩
  | 3 => ⟨⟨false, 6, 0⟩, 2, 8⟩
  | 4 => ⟨⟨true, 0, 2⟩, 1, 2⟩
  | 5 => ⟨⟨true, 1, 4⟩, 3, 5⟩
  | 6 => ⟨⟨true, 2, 1⟩, 7, 1⟩
  | 7 => ⟨⟨true, 3, 0⟩, 2, 3⟩
  | 8 => ⟨⟨true, 4, 1⟩, 7, 1⟩
  | 9 => ⟨⟨true, 4, 3⟩, 0, 4⟩
  | 10 => ⟨⟨true, 5, 2⟩, 1, 2⟩
  | _ => ⟨⟨true, 5, 4⟩, 1, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 6, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 12))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 6, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 12) (by decide)

end task_06

namespace task_07

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := none
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 1⟩, 2, 3⟩
  | 1 => ⟨⟨true, 1, 2⟩, 0, 2⟩
  | _ => ⟨⟨true, 2, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 3) (by decide)

end task_07

namespace task_08

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 0
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 2⟩, 0, 2⟩
  | 1 => ⟨⟨false, 2, 0⟩, 6, 1⟩
  | _ => ⟨⟨false, 7, 1⟩, 2, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (2 : Fin 3) (by decide)

end task_08

namespace task_09

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 1
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 1⟩, 2, 3⟩
  | 1 => ⟨⟨true, 1, 2⟩, 0, 2⟩
  | _ => ⟨⟨true, 2, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (0 : Fin 3) (by decide)

end task_09

namespace task_10

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 2
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 3) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 2⟩, 0, 2⟩
  | 1 => ⟨⟨false, 7, 1⟩, 2, 3⟩
  | _ => ⟨⟨true, 2, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 3) (by decide)

end task_10

namespace task_11

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 3
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 4⟩, 3, 3⟩
  | 1 => ⟨⟨false, 4, 3⟩, 0, 2⟩
  | 2 => ⟨⟨false, 7, 1⟩, 4, 4⟩
  | _ => ⟨⟨true, 3, 0⟩, 6, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (2 : Fin 4) (by decide)

end task_11

namespace task_12

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 4
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 4) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 4⟩, 3, 3⟩
  | 1 => ⟨⟨false, 7, 1⟩, 4, 4⟩
  | 2 => ⟨⟨true, 3, 0⟩, 6, 1⟩
  | _ => ⟨⟨true, 4, 3⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (1 : Fin 4) (by decide)

end task_12

namespace task_13

def task : Task 8 where
  adj := adj
  inside v := decide (v.val < 6)
  target := some 5
  allowedExit v := decide (v.val = 6)

def rows (i : Fin 12) : Task.Row 8 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 2⟩, 5, 7⟩
  | 1 => ⟨⟨false, 2, 5⟩, 3, 6⟩
  | 2 => ⟨⟨false, 4, 5⟩, 2, 3⟩
  | 3 => ⟨⟨false, 7, 1⟩, 2, 8⟩
  | 4 => ⟨⟨true, 0, 3⟩, 4, 5⟩
  | 5 => ⟨⟨true, 1, 2⟩, 0, 2⟩
  | 6 => ⟨⟨true, 2, 0⟩, 6, 1⟩
  | 7 => ⟨⟨true, 3, 0⟩, 6, 1⟩
  | 8 => ⟨⟨true, 3, 4⟩, 1, 4⟩
  | 9 => ⟨⟨true, 4, 1⟩, 2, 3⟩
  | 10 => ⟨⟨true, 5, 2⟩, 0, 2⟩
  | _ => ⟨⟨true, 5, 3⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 12))

theorem wins_bounded : task.MetricForcesWithin graph_valid 12 ⟨false, 7, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    12 (3 : Fin 12) (by decide)

end task_13

end triangular_prism_minus_triangle_edge

namespace cube_minus_vertex

def adj (u v : Fin 10) : Bool :=
  match u.val, v.val with
  | 0, 1 => true
  | 0, 2 => true
  | 0, 4 => true
  | 1, 0 => true
  | 1, 3 => true
  | 1, 5 => true
  | 2, 0 => true
  | 2, 3 => true
  | 2, 6 => true
  | 3, 1 => true
  | 3, 2 => true
  | 3, 7 => true
  | 4, 0 => true
  | 4, 5 => true
  | 4, 6 => true
  | 5, 1 => true
  | 5, 4 => true
  | 5, 8 => true
  | 6, 2 => true
  | 6, 4 => true
  | 6, 9 => true
  | 7, 3 => true
  | 8, 5 => true
  | 9, 6 => true
  | _, _ => false

namespace task_00

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 3⟩, 1, 3⟩
  | 1 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 3, 1⟩, 5, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_00

namespace task_01

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 3⟩, 2, 3⟩
  | 1 => ⟨⟨true, 2, 6⟩, 9, 1⟩
  | _ => ⟨⟨true, 3, 2⟩, 6, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_01

namespace task_02

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 0
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 12) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 0⟩, 2, 3⟩
  | 1 => ⟨⟨false, 2, 0⟩, 1, 3⟩
  | 2 => ⟨⟨false, 3, 1⟩, 0, 4⟩
  | 3 => ⟨⟨false, 7, 3⟩, 1, 5⟩
  | 4 => ⟨⟨true, 0, 1⟩, 5, 2⟩
  | 5 => ⟨⟨true, 0, 2⟩, 6, 2⟩
  | 6 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | 7 => ⟨⟨true, 2, 6⟩, 9, 1⟩
  | 8 => ⟨⟨true, 3, 1⟩, 5, 2⟩
  | 9 => ⟨⟨true, 3, 2⟩, 6, 2⟩
  | 10 => ⟨⟨true, 4, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 4, 6⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 12))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (3 : Fin 12) (by decide)

end task_02

namespace task_03

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 1
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 1⟩, 5, 2⟩
  | 1 => ⟨⟨false, 7, 3⟩, 1, 3⟩
  | _ => ⟨⟨true, 1, 5⟩, 8, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_03

namespace task_04

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 2
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 3, 2⟩, 6, 2⟩
  | 1 => ⟨⟨false, 7, 3⟩, 2, 3⟩
  | _ => ⟨⟨true, 2, 6⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_04

namespace task_05

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 3
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 7, 3⟩, 1, 3⟩
  | 1 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 3, 1⟩, 5, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_05

namespace task_06

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 4
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 10) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 5, 2⟩
  | 1 => ⟨⟨false, 1, 0⟩, 4, 3⟩
  | 2 => ⟨⟨false, 2, 0⟩, 4, 3⟩
  | 3 => ⟨⟨false, 3, 1⟩, 0, 4⟩
  | 4 => ⟨⟨false, 5, 4⟩, 6, 2⟩
  | 5 => ⟨⟨false, 6, 4⟩, 5, 2⟩
  | 6 => ⟨⟨false, 7, 3⟩, 1, 5⟩
  | 7 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | 8 => ⟨⟨true, 4, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 4, 6⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (6 : Fin 10))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (6 : Fin 10) (by decide)

end task_06

namespace task_07

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 5
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 5⟩, 8, 1⟩
  | 1 => ⟨⟨false, 3, 1⟩, 5, 2⟩
  | _ => ⟨⟨false, 7, 3⟩, 1, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_07

namespace task_08

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 6
  allowedExit v := decide (v.val = 8) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 2, 6⟩, 9, 1⟩
  | 1 => ⟨⟨false, 3, 2⟩, 6, 2⟩
  | _ => ⟨⟨false, 7, 3⟩, 2, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 7, 3⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 7, 3⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_08

namespace task_09

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 8, 5⟩, 1, 3⟩
  | 1 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_09

namespace task_10

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 8, 5⟩, 4, 3⟩
  | 1 => ⟨⟨true, 4, 6⟩, 9, 1⟩
  | _ => ⟨⟨true, 5, 4⟩, 6, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_10

namespace task_11

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 0
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 11) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 0⟩, 2, 3⟩
  | 1 => ⟨⟨false, 4, 0⟩, 1, 3⟩
  | 2 => ⟨⟨false, 5, 1⟩, 0, 4⟩
  | 3 => ⟨⟨false, 8, 5⟩, 1, 5⟩
  | 4 => ⟨⟨true, 0, 1⟩, 3, 2⟩
  | 5 => ⟨⟨true, 0, 2⟩, 3, 2⟩
  | 6 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 7 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 8 => ⟨⟨true, 2, 6⟩, 9, 1⟩
  | 9 => ⟨⟨true, 3, 2⟩, 6, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 11))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (3 : Fin 11) (by decide)

end task_11

namespace task_12

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 1
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 5, 1⟩, 3, 2⟩
  | 1 => ⟨⟨false, 8, 5⟩, 1, 3⟩
  | _ => ⟨⟨true, 1, 3⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_12

namespace task_13

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 2
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 10) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 3, 2⟩
  | 1 => ⟨⟨false, 1, 0⟩, 2, 3⟩
  | 2 => ⟨⟨false, 3, 2⟩, 6, 2⟩
  | 3 => ⟨⟨false, 4, 0⟩, 2, 3⟩
  | 4 => ⟨⟨false, 5, 1⟩, 0, 4⟩
  | 5 => ⟨⟨false, 6, 2⟩, 3, 2⟩
  | 6 => ⟨⟨false, 8, 5⟩, 1, 5⟩
  | 7 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 8 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 2, 6⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (6 : Fin 10))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (6 : Fin 10) (by decide)

end task_13

namespace task_14

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 3
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 7, 1⟩
  | 1 => ⟨⟨false, 5, 1⟩, 3, 2⟩
  | _ => ⟨⟨false, 8, 5⟩, 1, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_14

namespace task_15

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 4
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 5, 4⟩, 6, 2⟩
  | 1 => ⟨⟨false, 8, 5⟩, 4, 3⟩
  | _ => ⟨⟨true, 4, 6⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_15

namespace task_16

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 5
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 8, 5⟩, 1, 3⟩
  | 1 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_16

namespace task_17

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 6
  allowedExit v := decide (v.val = 7) || decide (v.val = 9)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 4, 6⟩, 9, 1⟩
  | 1 => ⟨⟨false, 5, 4⟩, 6, 2⟩
  | _ => ⟨⟨false, 8, 5⟩, 4, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 5⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 8, 5⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_17

namespace task_18

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 7)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 9, 6⟩, 2, 3⟩
  | 1 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 6, 2⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_18

namespace task_19

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := none
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 9, 6⟩, 4, 3⟩
  | 1 => ⟨⟨true, 4, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 6, 4⟩, 5, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_19

namespace task_20

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 0
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 10) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 2, 0⟩, 1, 3⟩
  | 1 => ⟨⟨false, 4, 0⟩, 1, 3⟩
  | 2 => ⟨⟨false, 6, 2⟩, 0, 4⟩
  | 3 => ⟨⟨false, 9, 6⟩, 2, 5⟩
  | 4 => ⟨⟨true, 0, 1⟩, 3, 2⟩
  | 5 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 6 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | 7 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | 8 => ⟨⟨true, 3, 1⟩, 5, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 10))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (3 : Fin 10) (by decide)

end task_20

namespace task_21

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 1
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 10) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 1⟩, 3, 2⟩
  | 1 => ⟨⟨false, 2, 0⟩, 1, 3⟩
  | 2 => ⟨⟨false, 3, 1⟩, 5, 2⟩
  | 3 => ⟨⟨false, 4, 0⟩, 1, 3⟩
  | 4 => ⟨⟨false, 5, 1⟩, 3, 2⟩
  | 5 => ⟨⟨false, 6, 2⟩, 0, 4⟩
  | 6 => ⟨⟨false, 9, 6⟩, 2, 5⟩
  | 7 => ⟨⟨true, 1, 3⟩, 7, 1⟩
  | 8 => ⟨⟨true, 1, 5⟩, 8, 1⟩
  | _ => ⟨⟨true, 2, 3⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (6 : Fin 10))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (6 : Fin 10) (by decide)

end task_21

namespace task_22

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 2
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 2⟩, 3, 2⟩
  | 1 => ⟨⟨false, 9, 6⟩, 2, 3⟩
  | _ => ⟨⟨true, 2, 3⟩, 7, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_22

namespace task_23

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 3
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 2, 3⟩, 7, 1⟩
  | 1 => ⟨⟨false, 6, 2⟩, 3, 2⟩
  | _ => ⟨⟨false, 9, 6⟩, 2, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_23

namespace task_24

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 4
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 6, 4⟩, 5, 2⟩
  | 1 => ⟨⟨false, 9, 6⟩, 4, 3⟩
  | _ => ⟨⟨true, 4, 5⟩, 8, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (1 : Fin 3) (by decide)

end task_24

namespace task_25

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 5
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 4, 5⟩, 8, 1⟩
  | 1 => ⟨⟨false, 6, 4⟩, 5, 2⟩
  | _ => ⟨⟨false, 9, 6⟩, 4, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (2 : Fin 3) (by decide)

end task_25

namespace task_26

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 7)
  target := some 6
  allowedExit v := decide (v.val = 7) || decide (v.val = 8)

def rows (i : Fin 3) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 9, 6⟩, 2, 3⟩
  | 1 => ⟨⟨true, 2, 3⟩, 7, 1⟩
  | _ => ⟨⟨true, 6, 2⟩, 3, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 6⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 3))

theorem wins_bounded : task.MetricForcesWithin graph_valid 14 ⟨false, 9, 6⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    14 (0 : Fin 3) (by decide)

end task_26

end cube_minus_vertex

namespace cube_minus_edge

def adj (u v : Fin 10) : Bool :=
  match u.val, v.val with
  | 0, 2 => true
  | 0, 4 => true
  | 0, 8 => true
  | 1, 3 => true
  | 1, 5 => true
  | 1, 9 => true
  | 2, 0 => true
  | 2, 3 => true
  | 2, 6 => true
  | 3, 1 => true
  | 3, 2 => true
  | 3, 7 => true
  | 4, 0 => true
  | 4, 5 => true
  | 4, 6 => true
  | 5, 1 => true
  | 5, 4 => true
  | 5, 7 => true
  | 6, 2 => true
  | 6, 4 => true
  | 6, 7 => true
  | 7, 3 => true
  | 7, 5 => true
  | 7, 6 => true
  | 8, 0 => true
  | 9, 1 => true
  | _, _ => false

namespace task_00

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := none
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 8, 0⟩, 2, 4⟩
  | 1 => ⟨⟨true, 0, 2⟩, 3, 3⟩
  | 2 => ⟨⟨true, 2, 3⟩, 1, 2⟩
  | _ => ⟨⟨true, 3, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (0 : Fin 4) (by decide)

end task_00

namespace task_01

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 0
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 8, 0⟩, 2, 4⟩
  | 1 => ⟨⟨true, 0, 2⟩, 3, 3⟩
  | 2 => ⟨⟨true, 2, 3⟩, 1, 2⟩
  | _ => ⟨⟨true, 3, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (0 : Fin 4) (by decide)

end task_01

namespace task_02

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 1
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 3, 3⟩
  | 1 => ⟨⟨false, 2, 3⟩, 1, 2⟩
  | 2 => ⟨⟨false, 3, 1⟩, 9, 1⟩
  | _ => ⟨⟨false, 8, 0⟩, 2, 4⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (3 : Fin 4) (by decide)

end task_02

namespace task_03

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 2
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 3, 3⟩
  | 1 => ⟨⟨false, 8, 0⟩, 2, 4⟩
  | 2 => ⟨⟨true, 2, 3⟩, 1, 2⟩
  | _ => ⟨⟨true, 3, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (1 : Fin 4) (by decide)

end task_03

namespace task_04

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 3
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 3, 3⟩
  | 1 => ⟨⟨false, 2, 3⟩, 1, 2⟩
  | 2 => ⟨⟨false, 8, 0⟩, 2, 4⟩
  | _ => ⟨⟨true, 3, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (2 : Fin 4) (by decide)

end task_04

namespace task_05

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 4
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 5, 3⟩
  | 1 => ⟨⟨false, 8, 0⟩, 4, 4⟩
  | 2 => ⟨⟨true, 4, 5⟩, 1, 2⟩
  | _ => ⟨⟨true, 5, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (1 : Fin 4) (by decide)

end task_05

namespace task_06

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 5
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 4⟩, 5, 3⟩
  | 1 => ⟨⟨false, 4, 5⟩, 1, 2⟩
  | 2 => ⟨⟨false, 8, 0⟩, 4, 4⟩
  | _ => ⟨⟨true, 5, 1⟩, 9, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (2 : Fin 4) (by decide)

end task_06

namespace task_07

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 6
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 14) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 6, 5⟩
  | 1 => ⟨⟨false, 2, 6⟩, 4, 4⟩
  | 2 => ⟨⟨false, 4, 6⟩, 2, 4⟩
  | 3 => ⟨⟨false, 8, 0⟩, 2, 6⟩
  | 4 => ⟨⟨true, 0, 2⟩, 3, 3⟩
  | 5 => ⟨⟨true, 0, 4⟩, 5, 3⟩
  | 6 => ⟨⟨true, 2, 3⟩, 1, 2⟩
  | 7 => ⟨⟨true, 3, 1⟩, 9, 1⟩
  | 8 => ⟨⟨true, 4, 5⟩, 1, 2⟩
  | 9 => ⟨⟨true, 5, 1⟩, 9, 1⟩
  | 10 => ⟨⟨true, 6, 2⟩, 3, 3⟩
  | 11 => ⟨⟨true, 6, 4⟩, 5, 3⟩
  | 12 => ⟨⟨true, 7, 3⟩, 1, 2⟩
  | _ => ⟨⟨true, 7, 5⟩, 1, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 14))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (3 : Fin 14) (by decide)

end task_07

namespace task_08

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 7
  allowedExit v := decide (v.val = 9)

def rows (i : Fin 15) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 0, 2⟩, 3, 9⟩
  | 1 => ⟨⟨false, 2, 3⟩, 7, 8⟩
  | 2 => ⟨⟨false, 3, 7⟩, 5, 7⟩
  | 3 => ⟨⟨false, 6, 7⟩, 3, 3⟩
  | 4 => ⟨⟨false, 8, 0⟩, 2, 10⟩
  | 5 => ⟨⟨true, 0, 2⟩, 3, 3⟩
  | 6 => ⟨⟨true, 1, 5⟩, 4, 6⟩
  | 7 => ⟨⟨true, 2, 3⟩, 1, 2⟩
  | 8 => ⟨⟨true, 3, 1⟩, 9, 1⟩
  | 9 => ⟨⟨true, 4, 0⟩, 2, 4⟩
  | 10 => ⟨⟨true, 5, 1⟩, 9, 1⟩
  | 11 => ⟨⟨true, 5, 4⟩, 0, 5⟩
  | 12 => ⟨⟨true, 6, 2⟩, 3, 3⟩
  | 13 => ⟨⟨true, 7, 3⟩, 1, 2⟩
  | _ => ⟨⟨true, 7, 5⟩, 1, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 8, 0⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (4 : Fin 15))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 8, 0⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (4 : Fin 15) (by decide)

end task_08

namespace task_09

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := none
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 9, 1⟩, 3, 4⟩
  | 1 => ⟨⟨true, 1, 3⟩, 2, 3⟩
  | 2 => ⟨⟨true, 2, 0⟩, 8, 1⟩
  | _ => ⟨⟨true, 3, 2⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (0 : Fin 4) (by decide)

end task_09

namespace task_10

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 0
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 2, 3⟩
  | 1 => ⟨⟨false, 2, 0⟩, 8, 1⟩
  | 2 => ⟨⟨false, 3, 2⟩, 0, 2⟩
  | _ => ⟨⟨false, 9, 1⟩, 3, 4⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (3 : Fin 4) (by decide)

end task_10

namespace task_11

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 1
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 9, 1⟩, 3, 4⟩
  | 1 => ⟨⟨true, 1, 3⟩, 2, 3⟩
  | 2 => ⟨⟨true, 2, 0⟩, 8, 1⟩
  | _ => ⟨⟨true, 3, 2⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (0 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (0 : Fin 4) (by decide)

end task_11

namespace task_12

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 2
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 2, 3⟩
  | 1 => ⟨⟨false, 3, 2⟩, 0, 2⟩
  | 2 => ⟨⟨false, 9, 1⟩, 3, 4⟩
  | _ => ⟨⟨true, 2, 0⟩, 8, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (2 : Fin 4) (by decide)

end task_12

namespace task_13

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 3
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 2, 3⟩
  | 1 => ⟨⟨false, 9, 1⟩, 3, 4⟩
  | 2 => ⟨⟨true, 2, 0⟩, 8, 1⟩
  | _ => ⟨⟨true, 3, 2⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (1 : Fin 4) (by decide)

end task_13

namespace task_14

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 4
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 5⟩, 4, 3⟩
  | 1 => ⟨⟨false, 5, 4⟩, 0, 2⟩
  | 2 => ⟨⟨false, 9, 1⟩, 5, 4⟩
  | _ => ⟨⟨true, 4, 0⟩, 8, 1⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (2 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (2 : Fin 4) (by decide)

end task_14

namespace task_15

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 5
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 4) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 5⟩, 4, 3⟩
  | 1 => ⟨⟨false, 9, 1⟩, 5, 4⟩
  | 2 => ⟨⟨true, 4, 0⟩, 8, 1⟩
  | _ => ⟨⟨true, 5, 4⟩, 0, 2⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (1 : Fin 4))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (1 : Fin 4) (by decide)

end task_15

namespace task_16

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 6
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 15) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 2, 9⟩
  | 1 => ⟨⟨false, 2, 6⟩, 4, 7⟩
  | 2 => ⟨⟨false, 3, 2⟩, 6, 8⟩
  | 3 => ⟨⟨false, 7, 6⟩, 2, 3⟩
  | 4 => ⟨⟨false, 9, 1⟩, 3, 10⟩
  | 5 => ⟨⟨true, 0, 4⟩, 5, 6⟩
  | 6 => ⟨⟨true, 1, 3⟩, 2, 3⟩
  | 7 => ⟨⟨true, 2, 0⟩, 8, 1⟩
  | 8 => ⟨⟨true, 3, 2⟩, 0, 2⟩
  | 9 => ⟨⟨true, 4, 0⟩, 8, 1⟩
  | 10 => ⟨⟨true, 4, 5⟩, 1, 5⟩
  | 11 => ⟨⟨true, 5, 1⟩, 3, 4⟩
  | 12 => ⟨⟨true, 6, 2⟩, 0, 2⟩
  | 13 => ⟨⟨true, 6, 4⟩, 0, 2⟩
  | _ => ⟨⟨true, 7, 3⟩, 2, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (4 : Fin 15))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (4 : Fin 15) (by decide)

end task_16

namespace task_17

def task : Task 10 where
  adj := adj
  inside v := decide (v.val < 8)
  target := some 7
  allowedExit v := decide (v.val = 8)

def rows (i : Fin 14) : Task.Row 10 :=
  match i.val with
  | 0 => ⟨⟨false, 1, 3⟩, 7, 5⟩
  | 1 => ⟨⟨false, 3, 7⟩, 5, 4⟩
  | 2 => ⟨⟨false, 5, 7⟩, 3, 4⟩
  | 3 => ⟨⟨false, 9, 1⟩, 3, 6⟩
  | 4 => ⟨⟨true, 1, 3⟩, 2, 3⟩
  | 5 => ⟨⟨true, 1, 5⟩, 4, 3⟩
  | 6 => ⟨⟨true, 2, 0⟩, 8, 1⟩
  | 7 => ⟨⟨true, 3, 2⟩, 0, 2⟩
  | 8 => ⟨⟨true, 4, 0⟩, 8, 1⟩
  | 9 => ⟨⟨true, 5, 4⟩, 0, 2⟩
  | 10 => ⟨⟨true, 6, 2⟩, 0, 2⟩
  | 11 => ⟨⟨true, 6, 4⟩, 0, 2⟩
  | 12 => ⟨⟨true, 7, 3⟩, 2, 3⟩
  | _ => ⟨⟨true, 7, 5⟩, 4, 3⟩

theorem graph_valid : task.GoodGraph := by decide
theorem rows_valid : ∀ i, task.RowValid rows i := by decide

theorem wins : task.MetricForces graph_valid ⟨false, 9, 1⟩ := by
  exact task.forces_metric graph_valid
    (Task.certificate_sound task rows rows_valid (3 : Fin 14))

theorem wins_bounded : task.MetricForcesWithin graph_valid 16 ⟨false, 9, 1⟩ := by
  exact Task.certificate_bounded task graph_valid rows rows_valid
    16 (3 : Fin 14) (by decide)

end task_17

end cube_minus_edge

end ZombieDamage.Data
