import Solution
#print axioms ZombieMain.full_damage_within_iff
#print axioms ZombieMain.full_damage_iff
#print axioms ZombieMain.davila_conjecture_24
#print axioms ZombieMain.full_damage_of_clean_edge
#print axioms ZombieMain.recurrent_coverage_of_clean_edge
#print axioms ZombieMain.mobius_recurrent_coverage
#print axioms ZombieMain.four_boundary_edges
#print axioms ZombieMain.short_component_expansion
#print axioms ZombieMain.diamond_ring_sensor_bound
#print axioms ZombieMain.four_port_principle
#print axioms ZombieMain.cycle_union_classification
#print axioms ZombieMain.shortComponent_catalogue
#print axioms ZombieMain.component_routing_at
#print axioms ZombieMain.target_contract
#print axioms ZombieMain.clean_initialization
#print axioms ZombieMain.full_damage_without_clean
#print axioms ZombieMain.subgraph_port_bound
#print axioms ZombieMain.SurvivorController.run_exists
#print axioms ZombieMain.RouteMemory.stage_unbounded
#print axioms ZombieMain.RouteMemory.recurrent_departures



#print axioms ZombieDamage.Graph.cleanEdge_forces_reply
#print axioms ZombieDamage.Graph.geodesicReply_iff_commonNeighbor
#print axioms ZombieDamage.Task.safe_replies_are_geodesic
#print axioms ZombieDamage.Task.certificate_sound
#print axioms ZombieDamage.Task.forces_metric
#print axioms ZombieDamage.Task.certificate_bounded
#print axioms ZombieDamage.Graph.short_twoStep_closed
#print axioms ZombieDamage.Verified.finite_component_routing
#print axioms ZombieDamage.Graph.involution_blocks_recovery
#print axioms ZombieDamage.DiamondRing.central_pair_sensor
#print axioms ZombieDamage.FullGame.ForcesWithin.mono
#print axioms ZombieDamage.FullGame.ForcesWithin.pad
#print axioms ZombieDamage.FullGame.ForcesWithin.bind
#print axioms ZombieDamage.FullGame.ForcesWithin.preserve_set
#print axioms ZombieDamage.FullGame.safe_step
#print axioms ZombieDamage.Task.metricForcesWithin_fullGame
#print axioms ZombieDamage.FullGame.serve_list
#print axioms ZombieDamage.FullGame.fullDamage_of_contract
#print axioms ZombieDamage.Graph.MetricCertificate.distance
#print axioms ZombieDamage.Graph.MetricCertificate.geodesicReply_iff
#print axioms ZombieDamage.ExecutableGame.Input.reply_semantics
#print axioms ZombieDamage.ExecutableGame.Input.survivor_semantics
#print axioms ZombieDamage.FullGame.universal_vertex_not_fullDamage
#print axioms ZombieDamage.FullGame.pass_damages_source
#print axioms ZombieDamage.FullGame.forced_trace_prefix
#print axioms ZombieDamage.FullGame.forced_trace_route
#print axioms ZombieDamage.CycleGame.full_damage
#print axioms ZombieDamage.MobiusGame.full_damage
#print axioms ZombieDamage.PrismGame.full_damage
#print axioms ZombieDamage.FullGame.PositionalTrap.blocks
#print axioms ZombieDamage.Exceptions.not_full_damage
#print axioms ZombieDamage.GraphIso.fullDamage_iff
#print axioms ZombieDamage.ShortComponentModel.safe_metric
#print axioms ZombieDamage.ShortComponentModel.reply_lift
#print axioms ZombieDamage.ShortComponentModel.metricForcesWithin_ambient
#print axioms ZombieDamage.FullGame.fullDamage_iff_eventual
#print axioms ZombieDamage.Task.fullGame_metricForcesWithin
#print axioms ZombieDamage.OpenStrip.rail_step
#print axioms ZombieDamage.OpenStrip.rung_step
#print axioms ZombieDamage.OpenStrip.forward_route
#print axioms ZombieDamage.OpenStrip.open_route
#print axioms ZombieDamage.OpenStrip.cap_rail_step
#print axioms ZombieDamage.OpenStrip.metric_exit_contract
#print axioms ZombieDamage.OpenStrip.metric_target_contract
#print axioms ZombieDamage.TriangleRoute.prescribed_exit
#print axioms ZombieDamage.TriangleRoute.target_route
#print axioms ZombieDamage.DiamondRoute.through_middle
#print axioms ZombieDamage.DiamondRoute.target_route
#print axioms ZombieDamage.FullGame.PermissiveForces.iff_normalized
#print axioms ZombieDamage.FullGame.fullDamage_iff_permissive
#print axioms ZombieDamage.Data.K2_3.task_00.wins
#print axioms ZombieDamage.Data.K2_3.task_00.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_01.wins
#print axioms ZombieDamage.Data.K2_3.task_01.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_02.wins
#print axioms ZombieDamage.Data.K2_3.task_02.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_03.wins
#print axioms ZombieDamage.Data.K2_3.task_03.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_04.wins
#print axioms ZombieDamage.Data.K2_3.task_04.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_05.wins
#print axioms ZombieDamage.Data.K2_3.task_05.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_06.wins
#print axioms ZombieDamage.Data.K2_3.task_06.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_07.wins
#print axioms ZombieDamage.Data.K2_3.task_07.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_08.wins
#print axioms ZombieDamage.Data.K2_3.task_08.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_09.wins
#print axioms ZombieDamage.Data.K2_3.task_09.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_10.wins
#print axioms ZombieDamage.Data.K2_3.task_10.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_11.wins
#print axioms ZombieDamage.Data.K2_3.task_11.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_12.wins
#print axioms ZombieDamage.Data.K2_3.task_12.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_13.wins
#print axioms ZombieDamage.Data.K2_3.task_13.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_14.wins
#print axioms ZombieDamage.Data.K2_3.task_14.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_15.wins
#print axioms ZombieDamage.Data.K2_3.task_15.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_16.wins
#print axioms ZombieDamage.Data.K2_3.task_16.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_17.wins
#print axioms ZombieDamage.Data.K2_3.task_17.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_18.wins
#print axioms ZombieDamage.Data.K2_3.task_18.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_19.wins
#print axioms ZombieDamage.Data.K2_3.task_19.wins_bounded
#print axioms ZombieDamage.Data.K2_3.task_20.wins
#print axioms ZombieDamage.Data.K2_3.task_20.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_00.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_00.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_01.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_01.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_02.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_02.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_03.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_03.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_04.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_04.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_05.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_05.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_06.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_06.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_07.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_07.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_08.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_08.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_09.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_09.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_10.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_10.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_11.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_11.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_12.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_12.wins_bounded
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_13.wins
#print axioms ZombieDamage.Data.K3_3_minus_edge.task_13.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_00.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_00.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_01.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_01.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_02.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_02.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_03.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_03.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_04.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_04.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_05.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_05.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_06.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_06.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_07.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_07.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_08.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_08.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_09.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_09.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_10.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_10.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_11.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_11.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_12.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_12.wins_bounded
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_13.wins
#print axioms ZombieDamage.Data.triangular_prism_minus_triangle_edge.task_13.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_00.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_00.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_01.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_01.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_02.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_02.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_03.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_03.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_04.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_04.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_05.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_05.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_06.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_06.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_07.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_07.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_08.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_08.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_09.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_09.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_10.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_10.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_11.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_11.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_12.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_12.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_13.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_13.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_14.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_14.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_15.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_15.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_16.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_16.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_17.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_17.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_18.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_18.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_19.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_19.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_20.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_20.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_21.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_21.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_22.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_22.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_23.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_23.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_24.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_24.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_25.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_25.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_vertex.task_26.wins
#print axioms ZombieDamage.Data.cube_minus_vertex.task_26.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_00.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_00.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_01.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_01.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_02.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_02.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_03.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_03.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_04.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_04.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_05.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_05.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_06.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_06.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_07.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_07.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_08.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_08.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_09.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_09.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_10.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_10.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_11.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_11.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_12.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_12.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_13.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_13.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_14.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_14.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_15.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_15.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_16.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_16.wins_bounded
#print axioms ZombieDamage.Data.cube_minus_edge.task_17.wins
#print axioms ZombieDamage.Data.cube_minus_edge.task_17.wins_bounded

#print axioms ZombieDamage.FullGame.zombieDamageNumber_le_card
#print axioms ZombieDamage.FullGame.canForceDamage_iff_le_number
#print axioms ZombieDamage.FullGame.canForceDamage_iff_eventual
#print axioms ZombieDamage.FullGame.zombieDamageNumber_eq_card_iff
#print axioms ZombieMain.davila_conjecture_24_damage_number

-- Renderer-compatible theorem interfaces; original roots remain audited above.
#print axioms PalomarVerified.full_damage_within_iff
#print axioms PalomarVerified.full_damage_iff
#print axioms PalomarVerified.davila_conjecture_24
#print axioms PalomarVerified.full_damage_of_clean_edge
#print axioms PalomarVerified.recurrent_coverage_of_clean_edge
#print axioms PalomarVerified.four_boundary_edges
#print axioms PalomarVerified.short_component_expansion
#print axioms PalomarVerified.four_port_principle
#print axioms PalomarVerified.cycle_union_classification
#print axioms PalomarVerified.central_pair_sensor
#print axioms PalomarVerified.metric_exit_contract
#print axioms PalomarVerified.metric_target_contract
#print axioms PalomarVerified.davila_conjecture_24_damage_number
